[package]
name = "obj-viewer"
version = "0.1.0"
authors = ["jannes <jannes.drijkoningen@ac-systems.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elapsed = "*"
sdl2 = "0.32"
